# -*- perl -*-

use strict;
use warnings;
use Test::Simple tests => 40;
use Math::Palindrome ':all';


ok(previous_palindrome(1000) == 999);
ok(previous_palindrome(999) == 989);
ok(previous_palindrome(111) == 101);
ok(previous_palindrome(101) == 99);
ok(previous_palindrome(99) == 88);
ok(previous_palindrome(88) == 77);
ok(previous_palindrome(30) == 22);
ok(previous_palindrome(22) == 11);
ok(previous_palindrome(11) == 9);
ok(previous_palindrome(10) == 9);
ok(previous_palindrome(9) == 8);
ok(previous_palindrome(8) == 7);
ok(previous_palindrome(7) == 6);
ok(previous_palindrome(6) == 5);
ok(previous_palindrome(5) == 4);
ok(previous_palindrome(4) == 3);
ok(previous_palindrome(3) == 2);
ok(previous_palindrome(2) == 1);
ok(previous_palindrome(1000) != 998);
ok(previous_palindrome(999) != 988);
ok(previous_palindrome(111) != 100);
ok(previous_palindrome(101) != 98);
ok(previous_palindrome(99) != 89);
ok(previous_palindrome(88) != 78);
ok(previous_palindrome(30) != 23);
ok(previous_palindrome(22) != 10);
ok(previous_palindrome(11) != 10);
ok(previous_palindrome(10) != 8);
ok(previous_palindrome(9) != 7);
ok(previous_palindrome(8) != 6);
ok(previous_palindrome(7) != 5);
ok(previous_palindrome(6) != 4);
ok(previous_palindrome(5) != 3);
ok(previous_palindrome(4) != 2);
ok(previous_palindrome(3) != 1);
ok(previous_palindrome(2) != 0);
eval { previous_palindrome('abc') };
ok($@ =~ /non-negative integer/);
eval { previous_palindrome(-1) };
ok($@ =~ /non-negative integer/);
eval { previous_palindrome(1.5) };
ok($@ =~ /non-negative integer/);
eval { previous_palindrome(0) };
ok($@ =~ /natural numbers/);
